"""interest topic field

Revision ID: 1830be56c2a8
Revises: 99a6fa9f899c
Create Date: 2017-09-26 17:33:37.792583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1830be56c2a8'
down_revision = '99a6fa9f899c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('interest', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'interest')
    # ### end Alembic commands ###
