"""polls

Revision ID: 99a6fa9f899c
Revises: 95a3dcd3c6ed
Create Date: 2017-09-22 16:49:03.478406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a6fa9f899c'
down_revision = '95a3dcd3c6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_answers_deleted'), 'polls_answers', ['deleted'], unique=False)
    op.create_table('polls_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('poll_answer_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['poll_answer_id'], ['polls_answers.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polls_votes_deleted'), 'polls_votes', ['deleted'], unique=False)
    op.add_column(u'topics', sa.Column('poll', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'topics', 'poll')
    op.drop_index(op.f('ix_polls_votes_deleted'), table_name='polls_votes')
    op.drop_table('polls_votes')
    op.drop_index(op.f('ix_polls_answers_deleted'), table_name='polls_answers')
    op.drop_table('polls_answers')
    # ### end Alembic commands ###
