"""updated_at field

Revision ID: b8b351be2ba0
Revises: b73e67b82c56
Create Date: 2017-10-13 20:20:48.335530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b351be2ba0'
down_revision = 'b73e67b82c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('topics', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'updated_at')
    op.drop_column('comments', 'updated_at')
    # ### end Alembic commands ###
